### ISSUE TITLE
Install stopped working with Home Assistant 2022.7.3

### ISSUE THREAD

**Issue by calisro** [wernerhp/appdaemon_wasp#5]
This seems to have stopped working as of the latest HA.  Can't install it either.

Home Assistant 2022.7.3

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/hacs/repositories/base.py:626
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 13:41:02 (2 occurrences)
Last logged: 13:43:56

[547629640112] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/hacs/websocket/repository.py", line 212, in hacs_repository_download
    await repository.async_install()
  File "/config/custom_components/hacs/repositories/base.py", line 833, in async_install
    await self.async_install_repository()
  File "/config/custom_components/hacs/repositories/base.py", line 916, in async_install_repository
    await self.download_content()
  File "/config/custom_components/hacs/repositories/base.py", line 572, in download_content
    await self.download_repository_zip()
  File "/config/custom_components/hacs/repositories/base.py", line 626, in download_repository_zip
    zip_file.extractall(self.content.path.local, extractable)
  File "/usr/local/lib/python3.10/zipfile.py", line 1645, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "/usr/local/lib/python3.10/zipfile.py", line 1693, in _extract_member
    if member.is_dir():
  File "/usr/local/lib/python3.10/zipfile.py", line 530, in is_dir
    return self.filename[-1] == '/'
IndexError: string index out of range
```

Apolgies, I can't tell if this is a Wasp issue or a HACS?

**Comment by calisro** [comment]
https://github.com/hacs/integration/issues/2783
